In [5]:
# Numpy Broadcasting (2)
import numpy as np

a = np.arange( 3 )
b = np.ones( (3,3) ) + np.arange( 3 )
c = np.arange(3).reshape( (3,1) ) + np.arange(3)
# 배열 값 출력
print( "np.arange( 3 ) =>", a )
print( "np.ones( (3,3) ) =>", np.ones( (3,3) ), sep="\n" )
print( "np.ones( (3,3) ) + np.arange( 3 ) =>", b, sep="\n"  )
print( "np.arange(3).reshape( (3,1) ) + np.arange(3) =>", c, sep="\n"  )

np.arange( 3 ) => [0 1 2]
np.ones( (3,3) ) =>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
np.ones( (3,3) ) + np.arange( 3 ) =>
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
np.arange(3).reshape( (3,1) ) + np.arange(3) =>
[[0 1 2]
 [1 2 3]
 [2 3 4]]
