In [6]:
import numpy as np

def f(y_index, x_index):
   return 100*y_index + x_index*10 + 1
pass

a = np.fromfunction( f, (3, 4), dtype=int)

print( "a =", a, sep="\n")

a =
[[  1  11  21  31]
 [101 111 121 131]
 [201 211 221 231]]
