In [3]:
import numpy as np

a1 = np.arange( 1, 5 ) 
a2 = a1.reshape( 2, -1 ) 
a3 = np.array( [ [1, 2], [3, 4]])

b = np.tile( a2, (2, 3) )
c = a2.repeat( 3, axis=1 )
d = c.repeat( 2, axis=0 )

print( "a1 = np.arange( 1, 5 )", a1, sep="\n")
print( "-"*40 ) 
print( "a2 = a.reshape( 2, -1 )", a2, sep="\n" )
print( "-"*40 ) 
print( "a3 = np.array([[1,2],[3,4]])", a3, sep="\n" )
print( "-"*40 ) 
print( "b = np.tile( a2, (2, 3) )", b, sep="\n" )
print( "-"*40 ) 
print( "c = a2.repeat( 3, axis=1 )", c, sep="\n" )
print( "-"*40 ) 
print( "d = c.repeat( 2, axis=0 )", d, sep="\n" )

a1 = np.arange( 1, 5 )
[1 2 3 4]
----------------------------------------
a2 = a.reshape( 2, -1 )
[[1 2]
 [3 4]]
----------------------------------------
a3 = np.array([[1,2],[3,4]])
[[1 2]
 [3 4]]
----------------------------------------
b = np.tile( a2, (2, 3) )
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]
----------------------------------------
c = a2.repeat( 3, axis=1 )
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]
----------------------------------------
d = c.repeat( 2, axis=0 )
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]]
