In [1]:
import numpy as np

a = np.arange( 1, 16 ).reshape(3, -1) 
b = np.pad( a, ( (0, 1), (0, 0) ), constant_values=1)
c = np.pad( a, ( (0, 0), (0, 2) ) )
d = np.pad( a, 1 )

print( "a = np.arange( 1, 16 ).reshape(3, -1)", a, sep="\n" )
print( "-"*40 ) 
print( "b = np.pad( a, ( (0,1), (0,0) ), constant_values=1)", b, sep="\n")
print( "-"*40 ) 
print( "c = np.pad( a, ( (0,0), (0,2) ) )", c, sep="\n")
print( "-"*40 ) 
print( "d = np.pad( a, 1 )", d, sep="\n")

a = np.arange( 1, 16 ).reshape(3, -1)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
----------------------------------------
b = np.pad( a, ( (0,1), (0,0) ), constant_values=1)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 1  1  1  1  1]]
----------------------------------------
c = np.pad( a, ( (0,0), (0,2) ) )
[[ 1  2  3  4  5  0  0]
 [ 6  7  8  9 10  0  0]
 [11 12 13 14 15  0  0]]
----------------------------------------
d = np.pad( a, 1 )
[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0]]
