In [4]:
import numpy as np

# Matlab 코딩 스타일
i , j = np.arange(2), np.arange(3)

print( "i = ", i, "-"*40, sep="\n")
print( "j = ", j, "-"*40, sep="\n")


i , j = np.meshgrid( i, j, indexing="ij" )
a = j - i 

print( "i = ", i, "-"*40, sep="\n")
print( "j = ", j, "-"*40, sep="\n")
print( "a = j - i", a, "-"*40, sep="\n") 

i = 
[0 1]
----------------------------------------
j = 
[0 1 2]
----------------------------------------
i = 
[[0 0 0]
 [1 1 1]]
----------------------------------------
j = 
[[0 1 2]
 [0 1 2]]
----------------------------------------
a = j - i
[[ 0  1  2]
 [-1  0  1]]
----------------------------------------
