In [4]:
import numpy as np

a = np.arange(1, 9)
b = np.arange(1, 9).reshape(2, 2, 2)
c = np.array( [ [ [0]*4 ]*2 , [ [1]*4 ]*2 , [ [2]*4 ]*2 ] )

print( 'a = np.arange(1, 9) = ', a )
print( "-"*50  )
print( 'b = np.arange(1, 9).reshape(2, 2, 2) = ', b , sep='\n' )
print( "-"*50  )
print( "c = ", c, sep="\n" )
print( "-"*50  )
print( "c.shape = ", c.shape )
print( "-"*50  )
print( "len(c.shape) = ", len(c.shape) )
print( "-"*50  )
print( "c.ndim = ", c.ndim )
print( "-"*50  )


a = np.arange(1, 9) =  [1 2 3 4 5 6 7 8]
--------------------------------------------------
b = np.arange(1, 9).reshape(2, 2, 2) = 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------------------------------------------
c = 
[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[2 2 2 2]
  [2 2 2 2]]]
--------------------------------------------------
c.shape =  (3, 2, 4)
--------------------------------------------------
len(c.shape) =  3
--------------------------------------------------
c.ndim =  3
--------------------------------------------------
