In [4]:
import numpy as np

a0 = np.arange( 1, 13 ).reshape( 1, 4, 3 )
a1 = -a0
a = np.concatenate( ( a0, a1 ), axis=0 )
b = np.swapaxes( a, 0, 1 )

print( "np.arange( 1, 13 ) =", np.arange( 1, 13 ) )
print( "-"*60  ) 
print( "a0 = np.arange( 1, 13 ).reshape( 1, 4, 3 )", a0, sep="\n" )
print( "-"*60  ) 
print( "a1 = -a0", a1, sep="\n" )
print( "-"*60  ) 

print( "a = np.concatenate( ( a0, a1 ), axis=0 )", a, sep="\n" )
print( "-"*60  ) 
print( "a.shape = ", a.shape )
print( "-"*60  ) 

print( "b = np.swapaxes( a, 0, 1 )", b, sep="\n" )
print( "-"*60  ) 
print( "b.shape = ", b.shape )
print( "-"*60  ) 

np.arange( 1, 13 ) = [ 1  2  3  4  5  6  7  8  9 10 11 12]
------------------------------------------------------------
a0 = np.arange( 1, 13 ).reshape( 1, 4, 3 )
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
------------------------------------------------------------
a1 = -a0
[[[ -1  -2  -3]
  [ -4  -5  -6]
  [ -7  -8  -9]
  [-10 -11 -12]]]
------------------------------------------------------------
a = np.concatenate( ( a0, a1 ), axis=0 )
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]
  [ 10  11  12]]

 [[ -1  -2  -3]
  [ -4  -5  -6]
  [ -7  -8  -9]
  [-10 -11 -12]]]
------------------------------------------------------------
a.shape =  (2, 4, 3)
------------------------------------------------------------
b = np.swapaxes( a, 0, 1 )
[[[  1   2   3]
  [ -1  -2  -3]]

 [[  4   5   6]
  [ -4  -5  -6]]

 [[  7   8   9]
  [ -7  -8  -9]]

 [[ 10  11  12]
  [-10 -11 -12]]]
------------------------------------------------------------
b.shape =  (4, 2, 3)
-------------------------