In [3]:
import numpy as np

a0 = np.arange( 1, 13 ).reshape( 1, 4, 3 )
a1 = -a0
a = np.concatenate( ( a0, a1 ), axis=0 )
b = np.swapaxes( a, 1, 2 )

print( "a = ", a, sep="\n" )
print( "-"*60  ) 
print( "a.shape = ", a.shape )
print( "-"*60  ) 

print( "b = np.swapaxes( a, 1, 2 ) ", b, sep="\n" )
print( "-"*60  ) 
print( "b.shape = ", b.shape )
print( "-"*60  ) 

a = 
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]
  [ 10  11  12]]

 [[ -1  -2  -3]
  [ -4  -5  -6]
  [ -7  -8  -9]
  [-10 -11 -12]]]
------------------------------------------------------------
a.shape =  (2, 4, 3)
------------------------------------------------------------
b = np.swapaxes( a, 1, 2 ) 
[[[  1   4   7  10]
  [  2   5   8  11]
  [  3   6   9  12]]

 [[ -1  -4  -7 -10]
  [ -2  -5  -8 -11]
  [ -3  -6  -9 -12]]]
------------------------------------------------------------
b.shape =  (2, 3, 4)
------------------------------------------------------------
