In [5]:
import numpy as np 

d = np.full( (3, 2), 9 ) # 렬 갯수 3, 행 갯수 2의 행렬 생성
print( "np.full( (3, 2), 7 )", d, sep="\n")

print( "-"*40 )
e = np.eye( 3, 3 ) # 렬 갯수 3, 행 갯수 2의 행렬 생성
print( "np.eye( 3, 3 )", e, sep="\n")

print( "-"*40 )
f = np.eye( 3 ) # 렬 갯수 3, 행 갯수 2의 행렬 생성
print( "np.eye( 3 )", f, sep="\n")

print( "-"*40 )
f = np.eye( 5 ) # 렬 갯수 3, 행 갯수 2의 행렬 생성
print( "np.eye( 5 )", f, sep="\n")

print( "-"*40 )
g = np.empty( (3, 2) ) # 렬 갯수 3, 행 갯수 2의 행렬 생성
print( "np.empty( (3, 2) )", g, sep="\n")

np.full( (3, 2), 7 )
[[9 9]
 [9 9]
 [9 9]]
----------------------------------------
np.eye( 3, 3 )
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------------------------------------
np.eye( 3 )
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------------------------------------
np.eye( 5 )
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
----------------------------------------
np.empty( (3, 2) )
[[4.4e-323 4.4e-323]
 [4.4e-323 4.4e-323]
 [4.4e-323 4.4e-323]]
