In [1]:
import numpy as np 

# 3x2 행렬, 0에서 10미만 임의의 정수 값으로 균일분포 초기화
a = np.random.randint( 0, 10, (3, 2) )
print( "np.random.randint( 0, 10, (3, 2) )", a, sep="\n" )
print( "-"*40 )

# 3x2 행렬, 0에서 1미만 임의의 실수 값으로 균일분포 초기화
b = np.random.rand(3,2) 
print( "np.random.rand( (3, 2) )", b, sep="\n" )
print( "-"*40 )

# 3x2 행렬, 0에서 1미만 임의의 실수 값으로 균일분포 초기화
c = np.random.uniform(1, 10, (3,2) ) 
print( "np.random.uniform(1, 10, (3,2) )", c, sep="\n" )
print( "-"*40 ) 

np.random.randint( 0, 10, (3, 2) )
[[5 4]
 [7 6]
 [4 9]]
----------------------------------------
np.random.rand( (3, 2) )
[[0.01658723 0.13599994]
 [0.72725662 0.13580454]
 [0.36114959 0.5596859 ]]
----------------------------------------
np.random.uniform(1, 10, (3,2) )
[[2.91071391 7.19966069]
 [1.06763703 1.35494642]
 [6.00610685 9.3263496 ]]
----------------------------------------
