In [5]:
import numpy as np

def f(y, x):
   return 4*y + x + 1

a = np.fromfunction(f, (3, 4), dtype=int)

print( "a = ", a, sep="\n")
print( "-"*30 )

for i, row in enumerate(a):
   print( "row ", i + 1, " =", row )

print( "-"*30 )
for element in a.flat :
    print( element, end=",")
 

a = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------
row  1  = [1 2 3 4]
row  2  = [5 6 7 8]
row  3  = [ 9 10 11 12]
------------------------------
1,2,3,4,5,6,7,8,9,10,11,12,