In [2]:
import numpy as np

a = np.random.randint( 0, 10, (3, 4) )

print( "a =", a, sep="\n" )
print( "a.shape =", a.shape )
print( "a.ravel() =", a.ravel() )
print( "a.ravel().shape =", a.ravel().shape )
print( "a.reshape(2, 6) =", a.reshape(2, 6), sep="\n" )
print( "a.T =", a.T, sep="\n" )
print( "a.T.shape =", a.T.shape )

a =
[[2 6 7 9]
 [8 3 3 3]
 [3 5 9 1]]
a.shape = (3, 4)
a.ravel() = [2 6 7 9 8 3 3 3 3 5 9 1]
a.ravel().shape = (12,)
a.reshape(2, 6) =
[[2 6 7 9 8 3]
 [3 3 3 5 9 1]]
a.T =
[[2 8 3]
 [6 3 5]
 [7 3 9]
 [9 3 1]]
a.T.shape = (4, 3)
