In [1]:
import numpy as np

h = np.array( [ [1, 3, 5], [6, 8, 10], [11, 13, 15]])
i = np.insert( h, [1, 2], 0, axis=1)

u = np.array( [[1, 5], [6, 10], [11, 15]] )
w = np.array( [[2, 3, 4], [7, 8, 9], [12, 13, 14]])
x = np.insert(u, [1], w, axis=1)

v = np.array( [[1, 2, 3, 4, 5], [11, 12, 13, 14 ,15]])
p = np.insert( v, 1, 7, axis=0)

print( "h = ", h, sep="\n" )
print( "-"*40 )
print( "i = np.insert( h, [1, 2], 0, axis=1)", i, sep="\n" )
print( "-"*40 )

print( "u = ", u, sep="\n" )
print( "-"*40 )
print( "w = ", w, sep="\n" )
print( "-"*40 )
print( "x = np.insert(u, [1], w, axis=1)", x, sep="\n" )
print( "-"*40 )

print( "v = ", v, sep="\n" )
print( "-"*40 )
print( "np.insert( v, 1, 7, axis=0)", p, sep="\n" )

h = 
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]
----------------------------------------
i = np.insert( h, [1, 2], 0, axis=1)
[[ 1  0  3  0  5]
 [ 6  0  8  0 10]
 [11  0 13  0 15]]
----------------------------------------
u = 
[[ 1  5]
 [ 6 10]
 [11 15]]
----------------------------------------
w = 
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
----------------------------------------
x = np.insert(u, [1], w, axis=1)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
----------------------------------------
v = 
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
----------------------------------------
np.insert( v, 1, 7, axis=0)
[[ 1  2  3  4  5]
 [ 7  7  7  7  7]
 [11 12 13 14 15]]
