In [ ]:
import numpy as np

print( "np.arange( 1, 5 ) = ", np.arange( 1, 5 ) )
print( "-"*40 )

a = np.arange( 1, 5 ).reshape( -1, 2 )
print( "a.shape = ", a.shape )

i , j = np.indices( a.shape )

b = a[ i, j ]

c = a[ j, i ] 

print( "-"*40 )
print( "a = ", a, "-"*40, sep="\n" )
print( "i = ", i, "-"*40, sep="\n" )
print( "j = ", j, "-"*40, sep="\n" )
print( "b = a[ i, j ]", b, "-"*40, sep="\n" )
print( "c = a[ j, i ]", c, "-"*40, sep="\n" )

np.arange( 1, 5 ) =  [1 2 3 4]
----------------------------------------
a.shape =  (2, 2)
----------------------------------------
a = 
[[1 2]
 [3 4]]
----------------------------------------
i = 
[[0 0]
 [1 1]]
----------------------------------------
j = 
[[0 1]
 [0 1]]
----------------------------------------
b = a[ i, j ]
[[1 2]
 [3 4]]
----------------------------------------
c = a[ j, i ]
[[1 3]
 [2 4]]
----------------------------------------
