In [3]:
import numpy as np 

a = np.array( 
                [ 
                    [ 4, 8, 5 ] , 
                    [ 9, 3, 1] 
                 ] 
             )

print( 'a = ', a, sep='\n' )
print( "-"*50  )

a.sort()
print( 'a.sort() = ', a, sep='\n' )
print( "-"*50  )

a = np.array( [ [4, 8, 5], [9, 3, 1] ] )

a.sort(axis=0)
print( 'a.sort(axis=0) = ', a, sep='\n' )
print( "-"*50  )

a = np.array( [ [4, 8, 5], [9, 3, 1] ] )
a.sort(axis=1)
print( 'a.sort(axis=1) = ', a, sep='\n' )

a = 
[[4 8 5]
 [9 3 1]]
--------------------------------------------------
a.sort() = 
[[4 5 8]
 [1 3 9]]
--------------------------------------------------
a.sort(axis=0) = 
[[4 3 1]
 [9 8 5]]
--------------------------------------------------
a.sort(axis=1) = 
[[4 5 8]
 [1 3 9]]
