In [ ]:
import numpy as np

a = np.array( [7, 4, 6, 5] )
b = np.argsort( a )
c = a[ b ]

print( 'a = ', a )
print( 'b = np.argsort( a ) = ', b )
print( 'a[ b ] = ', c )
print( "-"*50  )

# 인덱스 순서, 수직(row, 행, y), 수평(column, 렬, x)
# 깊이(depth, z)

a = np.array( [ [7, 2, 9], [4, 3, 8],
               [6, 1, 7], [5, 0,4] ]  )

b = np.argsort( a[ : , 0 ] )
c = a[ b ]
print( 'a = ', a, sep='\n' )
print( 'b = np.argsort( a[:, 0] ) = ', b )
print( 'a[ b ] = ', c, sep='\n' )

a =  [7 4 6 5]
b = np.argsort( a ) =  [1 3 2 0]
a[ b ] =  [4 5 6 7]
--------------------------------------------------
a = 
[[7 2 9]
 [4 3 8]
 [6 1 7]
 [5 0 4]]
b = np.argsort( a[:, 0] ) =  [1 3 2 0]
a[ b ] = 
[[4 3 8]
 [5 0 4]
 [6 1 7]
 [7 2 9]]
