In [1]:
import numpy as np

a = np.array( [ [3,4], [2, 7], [1, 5], [2, 6] ] )
b = np.rot90(a)
c = np.lexsort( b )
d = a[c]

print( 'a = ', a , sep='\n' )
print( "-"*50  )
print( 'b = np.rot90(a) ', b , sep='\n' )
print( "-"*50  )
print( 'c = np.lexsort( b ) ', c , )
print( "-"*50  )
print( 'a[c] = ', d , sep='\n' )

a = 
[[3 4]
 [2 7]
 [1 5]
 [2 6]]
--------------------------------------------------
b = np.rot90(a) 
[[4 7 5 6]
 [3 2 1 2]]
--------------------------------------------------
c = np.lexsort( b )  [2 3 1 0]
--------------------------------------------------
a[c] = 
[[1 5]
 [2 6]
 [2 7]
 [3 4]]
