In [6]:
import numpy as np

def f(y, x) :
   return 4*y + x + 1

a = np.fromfunction(f, (3, 4), dtype=int)

print( "a =", a, sep="\n")
print( "a[ 1, 2 ] =", a[ 1, 2 ] )
print( "a[ 1, : ] =", a[ 1, : ] )
print( "a[ :, 2 ] =", a[ :, 2 ] )
print( "a[ :, 1:3] =", a[ :, 1:3], sep="\n" )
print( "a[ -2:, -2: ] =", a[ -2:, -2: ], sep="\n"  )
print( "a[ ::2, 1::2 ] =", a[ ::2, 1::2 ], sep="\n"  )

a =
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a[ 1, 2 ] = 7
a[ 1, : ] = [5 6 7 8]
a[ :, 2 ] = [ 3  7 11]
a[ :, 1:3] =
[[ 2  3]
 [ 6  7]
 [10 11]]
a[ -2:, -2: ] =
[[ 7  8]
 [11 12]]
a[ ::2, 1::2 ] =
[[ 2  4]
 [10 12]]
