In [1]:
import numpy as np 

a = np.array( [ [1, 2, 3 ], [4, 5, 6], [7, 8, 9] ] )
b = np.array( [ -1, 0, 1 ] )
c = np.array( [ [3], [6], [9] ] )
d = np.array( [ [1], [2], [3] ] )

print( "a = ", a, sep="\n" )
print( "-"*30 )
print( "a/9 =", a/9, sep="\n" )
print( "-"*30 )

print( "a = ", a, sep="\n" )
print( "-"*30 )
print( "b = ", b, sep="\n" )
print( "-"*30 )
print( "a*b =", a*b, sep="\n" )
print( "-"*30 ) 

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
a/9 =
[[0.11111111 0.22222222 0.33333333]
 [0.44444444 0.55555556 0.66666667]
 [0.77777778 0.88888889 1.        ]]
------------------------------
a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
b = 
[-1  0  1]
------------------------------
a*b =
[[-1  0  3]
 [-4  0  6]
 [-7  0  9]]
------------------------------
