In [4]:
import numpy as np 

a = np.array( [ [1, 2, 3 ], [4, 5, 6], [7, 8, 9] ] )
c = np.array( [ [3], [6], [9] ] )
d = np.array( [ [1], [2], [3] ] ) 

print( "a = ", a, sep="\n" )
print( "-"*30 )
print( "c = ", c, sep="\n" )
print( "-"*30 )
print( "a/c =", a/c, sep="\n" )
print( "-"*30 )

print( "a = ", a, sep="\n" )
print( "-"*30 )
print( "d = ", d, sep="\n" )
print( "-"*30 )

print( "a*d = ", a*d, sep="\n" )
print( "-"*30 )

print( "a = ", a, sep="\n" )
print( "-"*30 )
print( "d = ", d, sep="\n" )
print( "-"*30 )
print( "a@d = ", a@d, sep="\n" )
print( "-"*30 )

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
c = 
[[3]
 [6]
 [9]]
------------------------------
a/c =
[[0.33333333 0.66666667 1.        ]
 [0.66666667 0.83333333 1.        ]
 [0.77777778 0.88888889 1.        ]]
------------------------------
a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
d = 
[[1]
 [2]
 [3]]
------------------------------
a*d = 
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
------------------------------
a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
d = 
[[1]
 [2]
 [3]]
------------------------------
a@d = 
[[14]
 [32]
 [50]]
------------------------------
