In [1]:
import numpy as np 

a = np.array( [ 1, 2, 3 ] )
b = np.array( [ 1, 2, 3 ] )

print( "a = ", a )
print( "b = ", b )

print( "a@b = ", a@b )
print( "inner = ", np.dot(a, b) )
print( "outer = ", np.outer(a, b), sep="\n" )

a =  [1 2 3]
b =  [1 2 3]
a@b =  14
inner =  14
outer = 
[[1 2 3]
 [2 4 6]
 [3 6 9]]
