In [3]:
import numpy as np

a = np.array( [ [8, 0, 0, 6], [1, 4, 3, 0], [0, 3, 1, 9] ] )

print( "a = ", a, sep="\n" ) 
print( "a address = ", hex(id(a)) )
print( "-"*30 )

b = a.reshape( 3, -1 )
print( "b = ", b, sep="\n" )
print( "b address ", hex(id(b)) )
print( "-"*30 )

a.resize( 2, 6 )
print( "a = ", a, sep="\n" )
print( "a address = ", hex(id(a)) )
print( "-"*30 )

a = 
[[8 0 0 6]
 [1 4 3 0]
 [0 3 1 9]]
a address =  0x2b29dc2e550
------------------------------
b = 
[[8 0 0 6]
 [1 4 3 0]
 [0 3 1 9]]
b address  0x2b29dc2e3d0
------------------------------
a = 
[[8 0 0 6 1 4]
 [3 0 0 3 1 9]]
a address =  0x2b29dc2e550
------------------------------
