In [1]:
import numpy as np 

a = np.array( [ [1, 2, 3 ], [4, 5, 6] ] )
b = np.array( [ [1, 2, 3 ] ] )
c = np.array( [1, 2, 3 ] )

print( "a.shape = ", a.shape )
print( "a =", a, sep="\n" )
print( "a.T = ", a.T, sep="\n" )

print( "-"*40 )
print( "b.shape = ", b.shape )
print( "b = ", b, sep="\n" )
print( "b.T = ", b.T, sep="\n" )

print( "-"*40 )
print( "c.shape = ", c.shape )
print( "c = ", c, sep="\n" )
print( "c.T = ", c.T, sep="\n" )

a.shape =  (2, 3)
a =
[[1 2 3]
 [4 5 6]]
a.T = 
[[1 4]
 [2 5]
 [3 6]]
----------------------------------------
b.shape =  (1, 3)
b = 
[[1 2 3]]
b.T = 
[[1]
 [2]
 [3]]
----------------------------------------
c.shape =  (3,)
c = 
[1 2 3]
c.T = 
[1 2 3]
