In [1]:
import numpy as np

a = np.arange( 1, 16 ).reshape(3, -1)
b = np.append( a, np.zeros( (3, 2) ), axis=1 )
c = np.column_stack( (a, np.zeros( 3 )) )
d = np.append( a, np.ones( (1, 5) ), axis=0)

print( "a = ", a, sep="\n" )
print( "-"*40 )

print( "b = np.append( a, np.zeros((3, 2)), axis=1 )", b, sep="\n" )
print( "-"*40 )

print( "c = np.column_stack( (a, np.zeros( 3 )) )", c, sep="\n" )
print( "-"*40 )

print( "d = np.append( a, np.ones( (1, 5) ), axis=0)", d, sep="\n" )

a = 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
----------------------------------------
b = np.append( a, np.zeros((3, 2)), axis=1 )
[[ 1.  2.  3.  4.  5.  0.  0.]
 [ 6.  7.  8.  9. 10.  0.  0.]
 [11. 12. 13. 14. 15.  0.  0.]]
----------------------------------------
c = np.column_stack( (a, np.zeros( 3 )) )
[[ 1.  2.  3.  4.  5.  0.]
 [ 6.  7.  8.  9. 10.  0.]
 [11. 12. 13. 14. 15.  0.]]
----------------------------------------
d = np.append( a, np.ones( (1, 5) ), axis=0)
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [ 1.  1.  1.  1.  1.]]
