In [ ]:
import numpy as np

o = np.arange(1, 16)
a = np.arange(1, 16).reshape(3, -1)  
b = np.delete(a.copy(), [1, 3], axis=1)
c = np.delete(a.copy(), 1, axis=0)
d = np.delete(a.copy(), np.s_[1:-1], axis=1)
e = np.delete(a.copy(), slice(1,-1), axis=1)
print( "o = np.arange(1, 16)", o, sep="\n" )
print( "-"*40 )
print( "a = np.arange(1, 16).reshape(3, -1)", a, sep="\n" )
print( "-"*40 )
print( "b = np.delete(a.copy(), [1, 3], axis=1)", b, sep="\n" )
print( "-"*40 )
print( "c = np.delete(a.copy(), 1, axis=0)", c, sep="\n" )
print( "-"*40 ) 
print( "d = np.delete(a.copy(), np.s_[1:-1], axis=1)", d, sep="\n" )
print( "-"*40 )
print( "e = np.delete(a.copy(), slice(1,-1), axis=1)", e, sep="\n" )

o = np.arange(1, 16)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
----------------------------------------
a = np.arange(1, 16).reshape(3, -1)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
----------------------------------------
b = np.delete(a.copy(), [1, 3], axis=1)
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]
----------------------------------------
c = np.delete(a.copy(), 1, axis=0)
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
----------------------------------------
d = np.delete(a.copy(), np.s_[1:-1], axis=1)
[[ 1  5]
 [ 6 10]
 [11 15]]
----------------------------------------
e = np.delete(a.copy(), slice(1,-1), axis=1)
[[ 1  5]
 [ 6 10]
 [11 15]]
