In [1]:
import numpy as np

# C 코딩 스타일
a = np.empty( (2, 3), np.int8 )

print( "a = np.empty( (2, 3), np.int8 )", a, sep="\n" )
print( "-"*50 )

for i in range(2):
    for j in range(3) :
        a[ i, j ] = ( j - i )
    pass
pass

print( "a = ", a, sep="\n") 

a = np.empty( (2, 3), np.int8 )
[[  8 -15   3]
 [  3   1   9]]
--------------------------------------------------
a = 
[[ 0  1  2]
 [-1  0  1]]
