In [2]:
import numpy as np 

# Numpy 코딩 스타일
i, j = np.arange(2), np.arange(3)

print( "i = ", i, "-"*40, sep="\n")
print( "j = ", j, "-"*40, sep="\n")

i, j = np.meshgrid( i, j, sparse=1, indexing="ij" )
a = j - i 

print( "i = ", i, "-"*40, sep="\n")
print( "j = ", j, "-"*40, sep="\n")
print( "a = ", a, "-"*40, sep="\n")

i = 
[0 1]
----------------------------------------
j = 
[0 1 2]
----------------------------------------
i = 
[[0]
 [1]]
----------------------------------------
j = 
[[0 1 2]]
----------------------------------------
a = 
[[ 0  1  2]
 [-1  0  1]]
----------------------------------------
