In [ ]:
import numpy as np 

a = np.arange( 1, 7 ).reshape( 2, -1 )

print( "np.arange( 1, 7 ) =", np.arange( 1, 7 ), sep="\n" )
print( "-"*50  )
print( "a = np.arange( 1, 7 ).reshape( 2, -1 )", a, sep="\n" )
print( "-"*50  )
print( "np.any( a>5 ) =", np.any( a>5 ) )
print( "np.any( a>5, axis=0 ) =", np.any( a>5, axis=0 ) )
print( "np.any( a>5, axis=1 ) =", np.any( a>5, axis=1 ))

np.arange( 1, 7 ) =
[1 2 3 4 5 6]
--------------------------------------------------
a = np.arange( 1, 7 ).reshape( 2, -1 )
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
np.any( a>5 ) = True
np.any( a>5, axis=0 ) = [False False  True]
np.any( a>5, axis=1 ) = [False  True]
