In [2]:
import numpy as np

a = np.array( [ [ [0, 1, 2] ]*4 ]*2 ) 
b = np.array( [ [ [0]*4 ]*2, [ [1]*4 ]*2, [ [2]*4 ]*2 ] )
c = np.dstack( [ [ [0]*4 ]*2, [ [1]*4 ]*2, [ [2]*4 ]*2 ] )

print( "a = ", a, sep="\n" )
print( "-"*50  ) 
print( "a.shape = ", a.shape )
print( "-"*50  ) 

print( "b = ", b, sep="\n" )
print( "-"*50  ) 
print( "b.shape = ", b.shape )
print( "-"*50  ) 

print( "c = ", c, sep="\n" )
print( "-"*50  ) 
print( "c.shape = ", c.shape )


a = 
[[[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]]
--------------------------------------------------
a.shape =  (2, 4, 3)
--------------------------------------------------
b = 
[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[2 2 2 2]
  [2 2 2 2]]]
--------------------------------------------------
b.shape =  (3, 2, 4)
--------------------------------------------------
c = 
[[[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]]
--------------------------------------------------
c.shape =  (2, 4, 3)
