In [13]:
import numpy as np

a = np.arange(1, 25).reshape(2, 3, 4)
b = np.arange(1, 17).reshape(2, 2, 4)
c = np.hstack( (a, b ) )

print( "np.arange(1, 25) = ", np.arange(1, 25) )
print( "a = np.arange(1, 25).reshape(2, 3, 4) = ", a, sep="\n" )
print( "-"*60  ) 
print( "a.shape = ", a.shape )
print( "-"*60  )  

print( "np.arange(1, 17) = ", np.arange(1, 17) )
print( "b = np.arange(1, 17).reshape(2, 2, 4) = ", b, sep="\n" )
print( "-"*60  ) 
print( "b.shape = ", b.shape )
print( "-"*60  ) 

print( "c = ", c, sep="\n" )
print( "-"*60  ) 
print( "c.shape = ", c.shape )
print( "-"*60  ) 

np.arange(1, 25) =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
a = np.arange(1, 25).reshape(2, 3, 4) = 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
------------------------------------------------------------
a.shape =  (2, 3, 4)
------------------------------------------------------------
np.arange(1, 17) =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
b = np.arange(1, 17).reshape(2, 2, 4) = 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
------------------------------------------------------------
b.shape =  (2, 2, 4)
------------------------------------------------------------
c = 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [ 1  2  3  4]
  [ 5  6  7  8]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]
  [ 9 10 11 12]
  [13 14 15 16]]]
------------------------------------------------------------
c.shape =  (2, 5, 4)
-------------------------------------------------